### ISSUE TITLE
Migrate Laevigata Prod to Hyrax 2.2

### ISSUE THREAD

**Issue by no-reply** [curationexperts/laevigata#1038]

**Comment by mark-dce** [comment]
**TODO**
- [ ] In production, while we are doing the migration, increase the database connection pool to match the number of sidekiq threads we settle on
- [ ] Disable submission on live production
- [ ] Copy existing data to production candidate server
- [ ] Ensure latest code release is deployed
- [ ] Run migration
- [ ] Validate content
- [ ] Put in production!
