### ISSUE TITLE
Get feature specs working

### ISSUE THREAD

**Issue by val99erie** [curationexperts/laevigata#1736]
In `spec/rails_helper.rb` there is code that disables almost all feature specs if the environment variable is set `NEW_UI_ENABLED=true`.

It is understandable that the feature specs based on the old form UI won't be able to run, but we have a lot of feature specs that aren't related to the ETD form at all, and we need to get those running.

**Tasks:**

- [x] For all feature specs that don't directly involve the ETD form, make sure the specs can be run with `NEW_UI_ENABLED=true`.

- [x] Update the Travis build, if needed, to make sure the feature specs run on CI with `NEW_UI_ENABLED=true`.

- [x] For feature specs that depend on the old UI (the ones that involve the ETD form):  Just leave them in place for now, but make sure they are disabled/skipped when `NEW_UI_ENABLED=true`.  They should get deleted in the future as part of the work to remove the old UI code.
