### ISSUE TITLE
Create a checklist of tasks that need to happen for the real cutover

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#2050]
Draw a timeline of cutover events
- [ ] When we bring each system down
- [ ] When we bring each system up
- [ ] When we capture backups
- [ ] Which systems need to go into read only mode when
- [ ] Where we restore backups to
- [ ] When we need to schedule prod down time 
- [ ] Switch backups over to backup the new systems
- [ ] Confirm we can restore a backup from the new system to qa or staging
- [ ] Switch monitoring over to monitoring the new systems 
- [ ] Reboot newly built systems & make sure they come back up as expected

**Comment by mark-dce** [comment]
We'll rewrite this ticket as part of the plan to update to Ubuntu 20.04 LTS
