### ISSUE TITLE
User Interface for About Me tab

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#241]
**DETAILS**
Create the About Me tab according to the layout of the below wireframe. Functionality for this tab is captured in Ticket #283.

**ACCEPTANCE CRITERIA**
- [x] The About Me tab should first in the navigation
- [x] The tab should be clearly labeled  
- [x] There should an area designated for a brief description
- [x] All of the form fields / drop-downs should appear in the same order as the wireframes.
- [x] All of the form fields / down-downs should be clearly labeled.
- [x] Ensure thorough testing for the view exists as part of the CI suite or an external testing suite

**WIREFRAME (updated 6/2/17)** 
https://emory.box.com/s/81oqmmp1q1g78czadl2g39z5h0ze7zx2

**Comment by shanitajohn** [comment]
**FIELDS & DROPDOWNS**
- [ ] Student Name
- [ ] Graduation Date - Ticket #193
- [ ] Post Graduation Email 
- [ ] School - Ticket #244
- [ ] Department / Program - Tickets #156
- [ ] Sub-field
- [ ] Degree
- [ ] I Am Submitting - Tickets #177 & #223
- [ ] Committee Chair / Thesis Advisor
- [ ] Committee Members - 
- [ ] Partnering Agency (Rollins Only) - Tickets #187

**Comment by shanitajohn** [comment]
Metadata Spreadsheet: 
https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0
