### ISSUE TITLE
About My ETD tab User Interface

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#242]
**DETAILS**
Create the About My ETD tab according to the layout of the below wireframe. Additional tickets will be created to express the specific functionality of each field/drop down. 

**ACCEPTANCE CRITERIA**
- [x] The About My ETD tab should come after "About Me" in the navigation
- [x] The tab should be clearly labeled  
- [x] There should an area designated for a brief description of the tab
- [x] All of the form fields / drop-downs should appear in the same order as the wireframes.
- [x] All of the form fields / down-downs should be clearly labeled.
- [x] Ensure thorough testing for the view exists as part of the CI suite or an external testing suite

**WIREFRAME (updated 6/2/17)** 
https://emory.box.com/s/e5vn73veumu94eq7bkybeqef7ffozoh5

**Comment by shanitajohn** [comment]
** FIELDS & DOWNDOWNS** 
- [ ] Title 
- [ ] Language - Ticket #204
- [ ] Abstract - Tickets #56 & #145
- [ ] Table of Content - Ticket #57
- [ ] Research Field - Ticket #188 & #149
- [ ] Keywords - Ticket #172
- [ ] Copyright & Patents Questions - Ticket #251

**Comment by jenlindner** [comment]
I want to split out another ticket for validating it and showing the green checkmark, and do a few more capybara specs for it, and the research field needs the primary field specified.

**Comment by jenlindner** [comment]
Managing the research fields required pulling in hydra-editor code and altering it, which took some effort to track down and implement. Going to change this ticket to an 8 because of that and the tinyMCE work.
