### ISSUE TITLE
Activate the "About Me" checkmark from the Submission Checklist

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#255]
**STORY**
As a student getting ready to submit my thesis, I want a visual checklist showing all the information I've filled in, so I know what's missing and what I have to fill in in order to have a complete submission. I want to be able to trust that when I have a green checkmark (as opposed to a red exclamation mark) next to the given tab, that I have met everything being ask of me. 

**ACCEPTANCE CRITERIA for Submission Checklist [item 1] About Me tab** 

In order for the About Me checkmark to appear (replacing the exclamation point), the following actions have to be taken on the About Me tab.

- [x] I have typed in the Student Name field
- [x] I have made a selection from the Graduation Date dropdown
- [x] I have typed in the Post-Graduation Email field
- [x] I have made a selection from the School dropdown  
- [x] I have made a selection from the Department / Program dropdown
- [x] I have made a selection from the Subfield dropdown (if enabled by the Department / Program dropdown) 
- [x] I have made a selection from the Degree dropdown
- [x] I have made a selection from the I Am Submitting dropdown 
- [x] I have selected a Faculty Type for Committee Chair / Thesis Advisor (Emory Faculty or Non-Emory Faculty)
- [x] I have typed in the Name field for Committee Chair / Thesis Advisor
- [x] If I have selected “Non-Emory Faculty” as my Faculty Type, I have typed in the Affiliation field
- [x] If I am a student of the Rollins School of Public Health, I have made a selection from the Partnering Agency dropdown
- [x] I have clicked the “Save About Me” button

**Comment by shanitajohn** [comment]
**WIREFRAME**
<img width="191" alt="screen shot 2017-05-26 at 3 40 16 pm" src="https://cloud.githubusercontent.com/assets/16900989/26511924/b23c2cfe-4229-11e7-83ed-2ecce3f04ba6.png">

**Comment by jenlindner** [comment]
I need to adjust the specific requirements for certain fields (the Partnering Agency becomes required if Rollins School is selected, Committee), but PR #319 addresses this ticket.
