### ISSUE TITLE
Activate the "About My ETD" checkmark from the Submission Checklist

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#268]
**STORY**
As Margo, an undergraduate student getting ready to submit my thesis, I want a visual checklist showing all the information I've filled in, so I know what's missing and what I have to fill in in order to have a complete submission. I want to be able to trust that when I have a green checkmark (as opposed to a red exclamation mark) next to the given tab, that I have met everything being ask of me. 

**ACCEPTANCE CRITERIA for Submission Checklist [item 2] About My ETD tab** 

In order for the About My ETD checkmark to appear (replacing the exclamation point), the following actions have to be taken on the About Me tab.

- [x] I have typed in the Title field
- [x] I have made a selection from the Language dropdown
- [x] I have typed in the WYSIWYG text editor for Abstract
- [x] I have typed in the WYSIWYG text editor for Table of Content
- [x] Using the dropdown menu, I have added a least one Research field
- [x] I have typed in the Keyword field

**Comment by shanitajohn** [comment]
**WIREFRAME**
<img width="207" alt="screen shot 2017-05-31 at 12 53 33 pm" src="https://cloud.githubusercontent.com/assets/16900989/26646653/0f3d7f44-4602-11e7-8c5b-62d528164c24.png">

**Comment by jenlindner** [comment]
Validating tinyMCE fields took some extra work, going to size this a 3.

**Comment by jenlindner** [comment]
Also this checks the language field as an input, as it is currently, but changing the code to check for input from a select is trivial.
