### ISSUE TITLE
Activate the "My PDF" checkmark from the Submission Checklist

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#269]
**STORY**
As a student getting ready to submit my thesis, I want a visual checklist showing all the information I've filled in, so I know what's missing and what I have to fill in in order to have a complete submission. I want to be able to trust that when I have a green checkmark (as opposed to a red exclamation mark) next to the given tab, that I have met everything being ask of me. 

**ACCEPTANCE CRITERIA for Submission Checklist [item 2] My PDF tab** 

In order for the My PDF checkmark to appear (replacing the exclamation point), the following actions have to be taken on the About Me tab.

- [ ] I have uploaded one file
- [ ] The file is in PDF format
- [ ] The file is within an acceptable file size

**Comment by shanitajohn** [comment]
**WIREFRAME**
<img width="203" alt="screen shot 2017-05-31 at 1 16 25 pm" src="https://cloud.githubusercontent.com/assets/16900989/26647073/b54185d8-4603-11e7-955a-c1217d4bf711.png">
