### ISSUE TITLE
About Me Tab Feature

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#283]
**DETAIL**
These are all of the fields required to capture the About Me & About My Program data for an ETD submission. When this ticket is closed, all of the About Me Tab functionality has been completed. 

Ticket #241 covers the UI of the About Me Tab. 

This is a way of verifying the metadata for About Me and My Program are fully functional. 

**FIELDS & DROPDOWNS**
- [x] Student Name
- [x] Graduation Date - Ticket #193
- [x] Post Graduation Email 
- [x] School - Ticket #244
- [x] Department / Program - Ticket #156
- [x] Sub-field
- [x] Degree
- [x] I Am Submitting - Tickets  #177 & #223
- [x] Committee Chair / Thesis Advisor
- [x] Committee Members - 
- [x] Partnering Agency (Rollins Only) - Tickets #187 & #140

**Metadata Spreadsheet**
https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0

**Comment by shanitajohn** [comment]
Related to Ticket #279 
Related to Ticket #280  
Related to Ticket #281
