### ISSUE TITLE
About My ETD tab Feature

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#284]
**DETAILS** 
This ticket captures all of the field functionality for the About My ETD Tab. Ticket #242 covers the UI for this tab. 

**FIELDS & DOWNDOWNS** 
- [x] Title 
- [x] Language - Ticket #204
- [x] Abstract - Tickets #56 & #145
- [x] Table of Content - Ticket #57
- [x] Research Field - Ticket #188 & #149
- [x] Keywords - Ticket #172
- [x] Copyright & Patents Questions - Ticket #251

**Comment by shanitajohn** [comment]
**Metadata Spreadsheet**
https://docs.google.com/spreadsheets/d/12EITagvnK3V8-6AJj7EWoPp4GrnY11HAtxmxrzgkL48/edit#gid=0
