### ISSUE TITLE
Tracking Ticket for Feeds

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#313]
- [x] Registrar's Sample Data 
- [ ] Registrar's Production Data
- [ ] ESD Sample Data - by June 17
- [ ] ESD Production Data - by June 17
- [ ] Emory Test Shibboleth - 
- [ ] Emory Production Shibboleth -

**Comment by shanitajohn** [comment]
We never used this ticket, closing.
