### ISSUE TITLE
Ensure we send the right degree codes to ProQuest

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#318]
**TASK** 
Review the degree.xls provided by ProQuest and: 

- [ ] Highlight degrees offered by Emory (@bnash and @fpici)
- [ ] Add any Emory degrees not in the xls (@bnash and @fpici)
- [ ] Ensure the [degree.yml](https://github.com/curationexperts/laevigata/blob/5de0035cb1e4ad0c70030606cd79e0ebfed7539d/config/authorities/degree.yml) file in laevigata is recording options that will be valid for ProQuest (@alexBLR)

**FILE**
https://emory.box.com/s/e6zpwwci4d9w0b1ekk75zt5p8d1zq33c

**Comment by shanitajohn** [comment]
Hi @fran, are you the right person to complete this task? Otherwise, please redirect me. Thanks!

**Comment by fpici** [comment]
@bnash108 Hi Shanita. I am passing this over to Bethany. She may be able to help with assigning this task. Hope this helps,

**Comment by bnash108** [comment]
@shanitajohn I have a question in to Jay here to see if it would be possible to export all the degree codes from current ETDs. If that is possible, would a list like that meet the needs of this ticket?

**Comment by shanitajohn** [comment]
@bnash108 I think that would satisfy the request but I'd like to confirm that with @bess first.

**Comment by shanitajohn** [comment]
@bnash108 I asked Bess, she's not sure that list would be enough because we don't know if there's anything happening behind the scenes to resolve to what ProQuest is expecting. But, if you are able to get it from Jay (and if it's simpler to do than highlighting) please go ahead! It's always helpful to see the what is currently being used.

**Comment by bnash108** [comment]
@shanitajohn I emailed my ProQuest contact for more details about their degree code list. Will report back once I hear from him.

**Comment by bess** [comment]
@bnash108 I believe we already have the list of degree codes that ProQuest will accept. We just don't want to present the students with that full list -- it's very long and most of the degree options are irrelevant to them. Instead, we'd prefer to present the students with only the degrees that are actually options for them, and then we'll cross-reference those with the ProQuest list and ensure we're recording them with the ProQuest terminology (e.g., "B.A." instead of "BA").

**Comment by bnash108** [comment]
@shanitajohn @bess My ProQuest contact confirmed what I suspected about their degree list. It is a list of ALL degree codes that ALL universities send them. We do not have to match what is on the list , but if we have any codes that aren't listed, I will contact ProQuest to have them add on their end. All of our degree codes should already be on the ProQuest list, but once Jay or @alexBLR is able to pull our full list from current ETDs I'll verify.

**Comment by bess** [comment]
The degree terms in https://github.com/curationexperts/laevigata/blob/master/config/authorities/degree.yml now match the controlled vocabulary expected by ProQuest.
