### ISSUE TITLE
Overall application UI cleanup & css styling

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#496]
All of the tabs on emory.curationexperts.com needs some degree of UI styling. Reference the below designs for placement. Styling should come from Emory pattern library. 

**Placement Designs (updated 07/10/17):** https://emory.box.com/s/jpg7umsu32rnqih4ykpx2irmwjhuvz8c

**Comment by shanitajohn** [comment]
**Case-Sensitivity on About Me**

About Me Tab
- [ ] Capitalize “Date” in Graduation Date label 
- [ ] Capitalize “Graduation” and “Email”  in Post Graduation Email 
- [ ] Capitalize “Agency” in Partnering Agency
- [ ] Capitalize “Agency” in “Add another Partnering Agency”
- [ ] Lowercase “another” in “Add another Committee Chair/Thesis Advisor”
- [ ] Lowercase “another” in “Add another Committee Chair Member”
- [ ] Change “I am submitting my” to “Submission Type”

**Comment by shanitajohn** [comment]
**My ETD Tab**

**ACCEPTANCE CRITERIA**
- [ ] Remove copy under “Language”
- [ ] Capitalize “Contents” in Table of Contents label 
- [ ] Change “Copyright Questions” to “Copyright & Patents”
- [ ] Indent Copyright & Patents questions 
- [ ] Indent Yes & No radio buttons, farther than questions (see example below)
- [ ] Bold a portion of question #3 (see example below)

![Screen Shot 2017-07-28 at 11.20.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ee0c2951415d4dbc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be04f50ac1b3262e372336e0a.png)

**Comment by shanitajohn** [comment]
**My PDF Tab**

**ACCEPTANCE CRITERIA**
- [ ] Hyperlink http://it.emory.edu/studentdigitallife/ in page description (See example)
- [ ] Align Green boxes with “Add Local Files” and “Cloud Providers” 
- [ ] Make “Browse Cloud” button the same size as “Add Primary PDF”
- [ ] Remove elipses (…) on Add Primary PDF

![Screen Shot 2017-07-28 at 11.25.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ee0c2954415b48bc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be04f50ad113561e771356e0a.png)

**Comment by shanitajohn** [comment]
**My Supplemental Files Tabs**

**ACCEPTANCE CRITERIA**
- [ ] add mailto: etd-help@LISTSERV.CC.EMORY.EDU page description 
- [ ] Green boxes with “Add Local Files” and “Cloud Providers” 
- [ ] Make “Browse Cloud” button the same size as “Add Primary PDF”
- [ ] Change “Add Supplementary files…” to “Add Supplemental Files”
- [ ] Remove elipses (…) on “Add Supplemental Files” and Add “Folder” 
- [ ] Reference ticket #554 for “I have no Supplemental Files” styling

**Comment by shanitajohn** [comment]
**My Embargoes Tab**
 
**ACCEPTANCE CRITERIA**
- [ ] Reference ticket #554 for “I do not want to embargo my thesis or dissertation” styling 
- [ ] Increase size of “What do you want to embargo?” (see example)
- [ ] Change “Which school are you in?” to “Select your school”
- [ ] Size “Select your school” to match “What do you want to embargo?”
- [ ] Increase size of “How long will the embargo last?” 
- [ ] Remove text under “How long will the embargo last?”

![Screen Shot 2017-07-28 at 11.54.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ee0c2e55415d4cbc30254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be04f53a5123362ee70316e0a.png)

**Comment by shanitajohn** [comment]
Moving styling of "I have no supplemental files" button to it's own ticket and closing this
