### ISSUE TITLE
Update submission checklist

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#561]
**ACCEPTANCE CRITERIA**
- [ ] Submission checklist should reflect tab names
- [ ] Remove extra what space to the right (See example)
- [x] Capitalize "ETD" (See ticket #522)

![Screen Shot 2017-07-28 at 12.09.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456fb6b7191a379ed0c2b58415f48bc21254d58eeb9cb74fce36f34985619e8d9390c7cc03a44abeed64ceb06ba208a1ed1b1bade4496fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be04f53a51b3167e472376e0a.png)
