### ISSUE TITLE
Editing ETDs

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#638]
Need to be sure all fields are handled correctly in edit view, that user experience is as expected.

**STORY**
As a student who has received by ETD back from my school reviewer for updates, I would like the following things to be true:
- [x] All of my data is editable.
- [x] My name is still in the Student Name field 
- [x] The graduation date I selected on submission is still in the graduation date dropdown
- [x] The email address I entered is still in the Post-Graduation Email field 
- [x] The school and department I entered are still in their respective dropdowns 
- [x] The degree I entered is still selected 
- [x] The submission type I chose is still selected 
- [x] The information about my committee chair is as I entered it
- [x] The information about my committee members is as I entered it
- [x] My title is as I entered it
- [x] My language is selected
- [x] My abstract content is entered ** - Issue #739
- [x] My table of contents are entered ** - Issue #739
- [x] My research field is selected
- [x] My keywords are entered
- [x] My copyright radio buttons are as I checked them, if I checked them

- [ ] My Primary PDF appears as it did when I uploaded it, in a row with filename, size and a delete button, and the ability to upload a new file - all of the 'create' functionality, including validations.  - Issue ##741
- [ ] My supplemental files appear as they did when I uploaded them, in rows displaying their filenames, sizes and the ability to delete each one - all of the 'create' functionality, including validations. - Issue #742 
- [ ] If I entered supplemental file metadata, it appears as I entered it, and each bit is editable. - Issue #742 
- [x] If I checked 'No supplemental files', the checkbox is checked and no other data is on the page until I uncheck it, at which point all of the upload elements should appear, as occurs on the create form. - Issue #742 
- [x] If I checked 'No embargoes', the checkbox is checked and no other data is on the page until I uncheck it, at which point all of the upload elements should appear, as occurs on the create form. - Issue #743
- [x] If have an embargo set, the items that I decided to embargo remain.  - Issue #743
- [x] If I have an embargo set, the school name remains  - Issue #743
- [x] If I have an embargo set, the duration remains  - Issue #743
- [x] Recheck all validations
- [x] I can resubmit my ETD.

**Comment by jenlindner** [comment]
@shanitajohn should the breadcrumbs appear at the top of the page?

**Comment by shanitajohn** [comment]
@jenlindner I don't think a breadcrumb is necessary only because you can move through the tabs in a non-linear manner. Is that what you mean? 

Also, yes, please investigate. It's not ideal, but I would prefer the student have to reformat their abstract over having to retype it. Thanks!

**Comment by jenlindner** [comment]
@shanitajohn I meant the links that appear at the top left, in a grey bar, they seem unnecessary (and cluttery) to me:
![breadcrumbs.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573a228f6ab6230e00445cbd/125516c66e82c728ace21e0d46ea869f228680bb9ae4bd50e611b2843b492d762a10e17132d0bb2cbc1a2d560a5818f8120c5844fcf8d87fa1b06878dc4e17ff933c0120996048e6edc00db513bf218e4e8fb7b98a4ec9e03f25e78b8f4e370c48.png)

**Comment by jenlindner** [comment]
@shanitajohn One other thing -- should the review tab be a little leaner? We don't need the user agreement again, of course, but also the generate preview seems a little clunky here.... Could you put this into your brain and see what it comes up with?

**Comment by shanitajohn** [comment]
** Flagged for follow-up, might need to create a second version of this work, one that is stripped down for Proquest submission and one that retains the formatting for the student to edit.

**Comment by val99erie** [comment]
@jenlindner and @bess I'm going to be working on a different project next week, so I won't be able to finish this story.  I'll take my name off it and move it back to the 'ready' column.

I added a bunch of `TODO:` entries in the `spec/features/edit_etd_spec.rb` for validating that the edit fields are all working properly.  You could just work through those TODOs to complete this story.

**Comment by bess** [comment]
@jenlindner and @shanitajohn Abstract and TOC should be stored in the app with all formatting in tact, and so they should be loaded back into the edit form with all formatting in tact. I do need to strip the formatting out when I send to ProQuest, but that's fine. I just send a stripped version of the file, I don't save that back to the object.

**Comment by jenlindner** [comment]
Thanks @bess.

**Comment by val99erie** [comment]
A minimal version of this story is complete.  I'm going to close this ticket, since the remaining requirements are fully covered in stories #741 and #742.  There may be some future work for UI changes or bug fixes, but those will be added as separate tickets.
